Update index.html
rebecalasconi/team-project-1 pull request #5
Opened 2024-06-04 18:19 UTC by NicuBu

2024-06-04 21:41 UTC, rebecalasconi commented on src/images/tsellers-img/kinderchocolate.png
nu ar fi trebuit sa fie format jpg?

2024-06-04 21:43 UTC, rebecalasconi commented on src/partials/tsellers.html
> +rgba(253, 146, 34, 1) ;">top</span> sellers</h1>
trebuie pusa in css culoarea

2024-06-04 21:49 UTC, rebecalasconi requested changes

2024-06-04 21:49 UTC, rebecalasconi commented on src/partials/tsellers.html
> +                <svg witdt="18px" height="18px">
width*

2024-06-04 21:49 UTC, rebecalasconi commented on src/partials/tsellers.html
> +                <svg witdt="18px" height="18px">
trece codul prin validator, apar erori

2024-06-05 06:22 UTC, NicuBu commented on src/images/tsellers-img/kinderchocolate.png
Le modific

2024-06-05 06:22 UTC, NicuBu commented on src/partials/tsellers.html
> +rgba(253, 146, 34, 1) ;">top</span> sellers</h1>
Ok

2024-06-05 06:22 UTC, NicuBu commented on src/partials/tsellers.html
> +                <svg witdt="18px" height="18px">
Ok :)

2024-06-05 08:55 UTC, rebecalasconi requested changes

2024-06-05 08:55 UTC, rebecalasconi commented on src/partials/tsellers.html
verifica liniile 46 si 48, sa ramana un singur descendent sub "input" si unul sub "label"

2024-06-05 09:23 UTC, rebecalasconi approved these changes

2024-06-05 09:23 UTC, merged